version: '3'

services:
  client:
    container_name: react-client
    build:
      context: ./client
      target: dev
    volumes:
      - ./client/src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    container_name: express-server
    build:
      context: ./services/server
      target: dev
    volumes:
      - ./services/server/src:/app/src
    ports:
      - 9090:9090
